### ISSUE TITLE
Selenium server error

### ISSUE THREAD

**Issue by nytche** [tkotosz/behat-browser-initialiser#1]
hello,

when I run your extension with selenium server, I got the following message:
"[WebDriver\Exception\UnknownError]  
  java.lang.String cannot be cast to java.lang.Number"

Do you know how to manage it?

**Comment by tkotosz** [comment]
The extension only uses the `resizeWindow`, `maximizeWindow` and `stop` methods of the `DriverInterface` (see https://github.com/Behat/Mink/blob/master/src/Behat/Mink/Driver/DriverInterface.php). The method calls can throw `UnsupportedDriverActionException` (see https://github.com/Behat/Mink/blob/master/src/Behat/Mink/Driver/CoreDriver.php#L435) if the functionalty is not implemented in the driver. But the selenium driver supports all of the required methods (see https://github.com/minkphp/MinkSelenium2Driver/blob/master/src/Selenium2Driver.php) and the error is not an `UnsupportedDriverActionException`, so I think this issue is not related to the `behat-browser-initialiser` extension. Sorry I have no idea what is the source of the issue, but if you manage to solve it please let me know.

**Comment by tkotosz** [comment]
@nytche I just run into the same issue, it turned out the mink extension doesn't convert the width/height values to int before passing it to the driver and I have used the string values from the behat yml config. I have converted these values to int now, the fix is included in the v1.0.1 package version. Please let me know if it solves the issue for you.
